### ISSUE TITLE
Cookies aren't being cleared out with hard refreshes, leading to a `deserialize` user error if a user record is deleted or the DB is dropped

### ISSUE THREAD

**Issue by nwalberts** [LaunchAcademy/generator-engage#122]
Chrome is holding on to cookies even with hard refreshes

Error: Failed to deserialize user out of session
    at pass (/Users/luisgaviria/challenges/ParkReviewProject/node_modules/passport/lib/authenticator.js:344:19)
    at deserialized (/Users/luisgaviria/challenges/ParkReviewProject/node_modules/passport/lib/authenticator.js:349:7)
    at default (file:///Users/luisgaviria/challenges/ParkReviewProject/server/src/authentication/deserializeUser.js:5:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    
The solve: open up your terminal in your browser, find the cookies and clear them out. More context in the QQ question below
https://learn.launchacademy.com/questions/11711

Looking for an automated fix

**Comment by dpickett** [comment]
ooo looks like our `deserializeUser` is short sighted and needs to consider this case: https://github.com/LaunchAcademy/generator-engage/blob/main/generators/server/templates/src/authentication/deserializeUser.js

Effectively it looks like we need to explicitly return `false` in the second argument in the case of a no longer persisted user. https://github.com/jaredhanson/passport/issues/6#issuecomment-4857287 

lol passport.
